var GAME_LEVELS = [
  ["                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                              x                               ",
   "                                                              x                               ",
   "                                                             xxx                              ",
   "                                                            xxxxx                             ",
   "                                                           xxxxxxx                            ",
   "                                                 o         xxxxxxx                            ",
   "                                                          xxxxxxxxx                           ",
   "                                                     xxxxxxxxxxxxxx                           ",
   "           xxx                                         &  xxxxxxxxx                           ",
   "   #        &                               xxxxx         xxxxxxxxx           o               ",
   "   x                           o            &  &          xxxxxxxxx           x               ",
   "                               x                          xxxxxxxxx           x               ",
   " =                      o                                +xxxxxxxxx           x               ",
   "                        x            xx                   xxxxxxxxx          xxx              ",
   "       @                             xxxx              o  xxxxxxxxx          xxx              ",
   "     xxxxx      xxxxx                xxxxxxx          xxxxxxxxxxxxx         xxxxx             ",
   "     xxxxx      xxxxx                xxxxxxxxxx           xxxxxxxxx        xxxxxxx            ",
   "     xxxxx      xxxxx                xxxxxxxxxxxx         xxxxxxxxx       xxxxxxxxx           ",
   "     xxxxx      xxxxx                xxxxxxxxxxxx         xxxxxxxxx       xxxxxxxxx           ",
   "     xxxxx      xxxxx                xxxxxxxxxxxx         xxxxxxxxx       xxxxxxxxx           ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                 xxx                          ",
    "                                  &                           ",
    "                                                              ",
    "                                                              ",
    "                                                              ",
    "                                                              ",
    "                                                              ",
    "                                                              ",
    "                                                              ",
    "                                                              ",
    "                                       o                      ",
    "                     xxx               x             o        ",
    "                      &                      o      xxxx      ",
    "            xxx                   o          x      xxxx      ",
    "             &                    x                 xxxx      ",
    "                                                    xxxx      ",
    " =                        o                         xxxx      ",
    "                          x                         xxxx      ",
    "                                                    xxxx      ",
    "                  o                                 xxxx      ",
    "         o        x                         o       xxxx      ",
    "   @     x                                          xxxx      ",
    " xxxx                                               xxxx      ",
    " xxxx                                               xxxx      ",
    " xxxx                                       +       xxxx      ",
    " xxxx                                               xxxx      ",
    " xxxx                                               xxxx      ",
    " xxxx                                       #       xxxx      ",
    " xxxx                                    xxxxxx     xxxx      ",
    " xxxx                                               xxxx      ",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! o !!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! x !!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["            !!!!!              ",
   "            !!!!!          #   ",
   "            !!!!!      xxxxxxxx",
   "  @         !!!!!       !!!!!!!",
   "xxxxxxx     !!!!!       !!!!!!!",
   "!!!!!!!   o !!!!!xx     !!!!!!!",
   "!!!!!!!  o  !!!!!       !!!!!!!",
   "!!!!!!!   o !!!!!       !!!!!!!",
   "!!!!!!!  o  !!!!!  *    !!!!!!!",
   "!!!!!!! o o !!!!!       !!!!!!!",
   "!!!!!!!  o  !!!!!     xx!!!!!!!",
   "!!!!!!!  oo !!!!!       !!!!!!!",
   "!!!!!!!  o  !!!!!       !!!!!!!",
   "!!!!!!!  o  !!!!!       !!!!!!!",
   "!!!!!!!  o  !!!!!xx     !!!!!!!",
   "!!!!!!! o o !!!!!       !!!!!!!",
   "!!!!!!!  o  !!!!!       !!!!!!!",
   "!!!!!!!  o  !!!!!       !!!!!!!",
   "!!!!!!!  o  !!!!!     xx!!!!!!!",
   "!!!!!!!  o  !!!!!       !!!!!!!",
   "!!!!!!!o o  !!!!!       !!!!!!!",
   "!!!!!!!  o  !!!!!       !!!!!!!",
   "!!!!!!!     !!!!!     xx!!!!!!!",
   "!!!!!!!     !!!!!       !!!!!!!",
   "!!!!!!!     !!!!!   *   !!!!!!!",
   "!!!!!!!     !!!!!       !!!!!!!",
   "!!!!!!!     !!!!!xx     !!!!!!!",
   "!!!!!!!     !!!!!       !!!!!!!",
   "!!!!!!!     !!!!!       !!!!!!!",
   "!!!!!!!       +       xx!!!!!!!",
   "!!!!!!!=                !!!!!!!",
   "!!!!!!!                 !!!!!!!",
   "!!!!!!!xxxxxxxxxxxxxxxxx!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                                 ",
    "  x    x   xxx   x   x          x   x  x  xx    x",
    "  x    x  x   x  x   x          x   x  x  x x   x",
    "    xx    x   x  x   x          x   x  x  x  x  x",
    "    xx    x   x  x   x          x x x  x  x   x x",
    "    xx     xxx    xxx            x x   x  x    xx",
    "         &          &         &         &        ",
    " =                                            =  ",
    "     o         o         o          o        o   ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                                 ",
    "   @                                         #   ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
